<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundemailcampaign');// Pour le texte ?>
    <?php
    $form = $this->form;
    $form->prepare();
    ?>

<h2><?php echo $this->translate('Add a Template'); ?></h2>
<?php echo $this->form()->openTag($form) ?>

    <div class="label-input">
        <?php echo $this->formHidden($form->get('id')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('title')); ?>
        <?php echo $this->formInput($form->get('title')); ?>
    </div>
    <p><?php echo $this->translate('Edit HTML code'); ?></p>
    <div class="label-input">
        <?php echo $this->formTextarea($form->get('htmlContent')); ?>
    </div>
    <p><?php echo $this->translate('Or upload an existing template'); ?></p>
    <div class="label-input">
        <?php echo $this->formFile($form->get('htmlFile')); ?>
    </div>

    <?php echo $this->formButton($form->get('submit')); ?>
<?php echo $this->form()->closeTag() ?>

<?php if ($this->preview) :?>
    <div id="preview">
        <img src="<?php echo $this->preview; ?>" alt="<?php echo get('title') ?> preview"/>
    </div>
<?php endif; ?>