<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundemailcampaign');// Pour le texte ?>
    <?php
    $form = $this->form;
    $form->prepare();
    ?>

<h2><?php echo $this->translate('Add a List'); ?></h2>
<?php echo $this->form()->openTag($form) ?>

    <div class="label-input">
        <?php echo $this->formHidden($form->get('id')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('name')); ?>
        <?php echo $this->formInput($form->get('name')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('description')); ?>
        <?php echo $this->formInput($form->get('description')); ?>
    </div>
    <p><?php echo $this->translate('Contacts'); ?></p>
    <div id = "subscriptions">
        <span data-template="
        <input type='hidden' name='subscriptions[__index__][id]' value=''/>
        <input type='hidden' name='subscriptions[__index__][mailingList]' value='<?php echo $form->get('id')->getValue(); ?>'/>
        <select name='subscriptions[__index__][contact]' >
        <option value=''><?php echo $this->translate('Select a contact'); ?></option>
        <?php foreach ($this->activeContacts as $contact) :?>
            <option value='<?php echo $contact->getId();?>'><?php echo $contact->getUser()->getEmail();?></option>
        <?php endforeach; ?>
        </select><button type='button' name='subscriptions[__index__][remove]' class='delete-button' value=''>Supprimer</button>"></span>

        <?php foreach ($form->get('subscriptions') as $subscription) : ?>
        <fieldset>
            <?php echo $this->formHidden($subscription->get('id')); ?>
            <?php echo $this->formHidden($subscription->get('mailingList')); ?>
            <?php echo $this->formSelect($subscription->get('contact')); ?>
            <?php echo $this->formButton($subscription->get('remove')); ?>
        </fieldset>
        <?php endforeach; ?>

       </div>

    <ul class="liste-buttons">
        <li class="btn-admin"><a href="#" onclick="add_contact()"><?php echo $this->translate('Add an other contact'); ?></a></li>
    </ul>

    <?php echo $this->formButton($form->get('submit')); ?>
<?php echo $this->form()->closeTag() ?>

<script>
    var template = $('#subscriptions > span');
    var datatemplate = $('#subscriptions > span').data('template');

    template.data('template', '<fieldset id="subscriptions__index__">'+datatemplate+'</fieldset>');

    function add_contact() {
        var currentCount = $('#subscriptions select').length;
        var template = $('#subscriptions > span').data('template');
        template = template.replace(/__index__/g, currentCount);
        $('#subscriptions').append(template);

        return false;
    }

</script>