<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundemailcampaign');// Pour le texte ?>
<?php $locale= $this->plugin('translate')->getTranslator()->getLocale(); ?>

<h2><?php echo $this->translate('Subscriptions') ?></h2>

<?php  if($this->subscriptions) :?>
    <table id="mailing_list">
        <thead>
            <tr>
                <th><?php echo $this->translate('Email') ?></th>
                <th><?php echo $this->translate('Lastname') ?></th>
                <th><?php echo $this->translate('Firstname') ?></th>
                <th><?php echo $this->translate('State') ?></th>
                <th><?php echo $this->translate('Created at') ?></th>
                <th><?php echo $this->translate('Updated at') ?></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->subscriptions as $subscription):?>
            <tr>
                <td><?php echo $subscription->getContact()->getUser()->getEmail(); ?></td>
                <td><?php echo $subscription->getContact()->getUser()->getLastname(); ?></td>
                <td><?php echo $subscription->getContact()->getUser()->getFirstname(); ?></td>
                <td><?php echo $subscription->getStatus(); ?></td>
                <td><?php echo $this->dateFormat($subscription->getCreatedAt(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, $locale); ?></td>
                <td><?php echo $this->dateFormat($subscription->getUpdatedAt(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, $locale); ?></td>

                <?php $deleteLink = $this->url('admin/email-campaign/lists/unsubscribe', array(
                        'listId' => $subscription->getMailingList()->getId(),
                        'contactId' => $subscription->getContact()->getId())
                    );?>
                <td>
                    <a href='<?php echo $deleteLink ?>'><?php echo $this->translate('Unsubscribe'); ?></a>
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
<?php endif; ?>
